# 2024-07-14 Spain vs England (Final)
- competition_id: 55
  season_id: 282
  game_id: 3943043

# 2024-07-10 Netherlands vs England (Semi-finals)
- competition_id: 55
  season_id: 282
  game_id: 3942819

# 2024-07-05 Portugal vs France (Quarter-finals)
- competition_id: 55
  season_id: 282
  game_id: 3942349

# 2024-07-01 France vs Belgium (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3941019

# 2024-06-29 Germany vs Denmark (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3940983

# 2024-06-24 Croatia vs Italy (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930178

# 2024-06-20 Denmark vs England (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930171

# 2024-06-26 Georgia vs Portugal (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938644
