# 2024-06-14 Germany vs Scotland (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930158

# 2024-06-15 Hungary vs Switzerland (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930159

# 2024-06-15 Spain vs Croatia (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930160

# 2024-06-15 Italy vs Albania (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930161

# 2024-06-16 Slovenia vs Denmark (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930162

# 2024-06-16 Serbia vs England (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930163

# 2024-06-16 Poland vs Netherlands (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938637

# 2024-06-17 Belgium vs Slovakia (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930164

# 2024-06-17 Austria vs France (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930165

# 2024-06-17 Romania vs Ukraine (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938638

# 2024-06-18 Portugal vs Czech Republic (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930166

# 2024-06-18 Turkey vs Georgia (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938639

# 2024-06-19 Croatia vs Albania (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930167

# 2024-06-19 Germany vs Hungary (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930168

# 2024-06-19 Scotland vs Switzerland (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930169

# 2024-06-20 Slovenia vs Serbia (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930170

# 2024-06-20 Spain vs Italy (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930172

# 2024-06-21 Netherlands vs France (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930173

# 2024-06-21 Slovakia vs Ukraine (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938640

# 2024-06-21 Poland vs Austria (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938641

# 2024-06-22 Turkey vs Portugal (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930174

# 2024-06-22 Belgium vs Romania (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930175

# 2024-06-22 Georgia vs Czech Republic (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938642

# 2024-06-23 Switzerland vs Germany (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930176

# 2024-06-23 Scotland vs Hungary (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930177

# 2024-06-24 Albania vs Spain (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930179

# 2024-06-25 Netherlands vs Austria (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930180

# 2024-06-25 England vs Slovenia (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930181

# 2024-06-25 Denmark vs Serbia (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930182

# 2024-06-25 France vs Poland (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938643

# 2024-06-26 Slovakia vs Romania (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930183

# 2024-06-26 Czech Republic vs Turkey (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3930184

# 2024-06-26 Ukraine vs Belgium (Group Stage)
- competition_id: 55
  season_id: 282
  game_id: 3938645

# 2024-06-29 Switzerland vs Italy (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3940878

# 2024-06-30 England vs Slovakia (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3941017

# 2024-06-30 Spain vs Georgia (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3941018

# 2024-07-01 Portugal vs Slovenia (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3941020

# 2024-07-02 Romania vs Netherlands (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3941021

# 2024-07-02 Austria vs Turkey (Round of 16)
- competition_id: 55
  season_id: 282
  game_id: 3941022

# 2024-07-05 Spain vs Germany (Quarter-finals)
- competition_id: 55
  season_id: 282
  game_id: 3942226

# 2024-07-06 England vs Switzerland (Quarter-finals)
- competition_id: 55
  season_id: 282
  game_id: 3942227

# 2024-07-06 Netherlands vs Turkey (Quarter-finals)
- competition_id: 55
  season_id: 282
  game_id: 3942382

# 2024-07-09 Spain vs France (Semi-finals)
- competition_id: 55
  season_id: 282
  game_id: 3942752
