
- competition_id: 55
  season_id: 282
  game_id: 3930158


- competition_id: 55
  season_id: 282
  game_id: 3930159


- competition_id: 55
  season_id: 282
  game_id: 3930160


- competition_id: 55
  season_id: 282
  game_id: 3930161


- competition_id: 55
  season_id: 282
  game_id: 3930162


- competition_id: 55
  season_id: 282
  game_id: 3930163


- competition_id: 55
  season_id: 282
  game_id: 3938637


- competition_id: 55
  season_id: 282
  game_id: 3930164


- competition_id: 55
  season_id: 282
  game_id: 3930165


- competition_id: 55
  season_id: 282
  game_id: 3938638


- competition_id: 55
  season_id: 282
  game_id: 3930166


- competition_id: 55
  season_id: 282
  game_id: 3938639


- competition_id: 55
  season_id: 282
  game_id: 3930167


- competition_id: 55
  season_id: 282
  game_id: 3930168


- competition_id: 55
  season_id: 282
  game_id: 3930169


- competition_id: 55
  season_id: 282
  game_id: 3930170


- competition_id: 55
  season_id: 282
  game_id: 3930172


- competition_id: 55
  season_id: 282
  game_id: 3930173


- competition_id: 55
  season_id: 282
  game_id: 3938640


- competition_id: 55
  season_id: 282
  game_id: 3938641


- competition_id: 55
  season_id: 282
  game_id: 3930174


- competition_id: 55
  season_id: 282
  game_id: 3930175


- competition_id: 55
  season_id: 282
  game_id: 3938642


- competition_id: 55
  season_id: 282
  game_id: 3930176


- competition_id: 55
  season_id: 282
  game_id: 3930177


- competition_id: 55
  season_id: 282
  game_id: 3930179


- competition_id: 55
  season_id: 282
  game_id: 3930180


- competition_id: 55
  season_id: 282
  game_id: 3930181


- competition_id: 55
  season_id: 282
  game_id: 3930182


- competition_id: 55
  season_id: 282
  game_id: 3938643


- competition_id: 55
  season_id: 282
  game_id: 3930183


- competition_id: 55
  season_id: 282
  game_id: 3930184


- competition_id: 55
  season_id: 282
  game_id: 3938645


- competition_id: 55
  season_id: 282
  game_id: 3940878


- competition_id: 55
  season_id: 282
  game_id: 3941017


- competition_id: 55
  season_id: 282
  game_id: 3941018


- competition_id: 55
  season_id: 282
  game_id: 3941020


- competition_id: 55
  season_id: 282
  game_id: 3941021


- competition_id: 55
  season_id: 282
  game_id: 3941022


- competition_id: 55
  season_id: 282
  game_id: 3942226


- competition_id: 55
  season_id: 282
  game_id: 3942227


- competition_id: 55
  season_id: 282
  game_id: 3942382


- competition_id: 55
  season_id: 282
  game_id: 3942752
